# Generated by Django 5.0.4 on 2025-01-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
