# Generated by Django 5.0.4 on 2025-01-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testt', '0005_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
