# Generated by Django 5.0.4 on 2025-01-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testt', '0008_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
