# Generated by Django 5.0.4 on 2025-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testt', '0009_remove_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
