# Generated by Django 5.0.4 on 2025-01-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testt', '0010_order_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
    ]
